<?php
return [  
'catalog'=>'catalog/index',
'product/([0-9]+)'=>'product/view/$1',    
'category/([0-9]+)/page-([0-9]+)'=>'catalog/category/$1/$2',  
'category/([0-9]+)'=>'catalog/category/$1',
'cart/add/([0-9]+)'=>'cart/add/$1',
'about'=>'about/index',
'cabinet/history' => 'cabinet/history',
'cabinet/edit' => 'cabinet/edit',
'cabinet' => 'cabinet/index',
'user/register' => 'user/register',
'user/login' => 'user/login',
'user/logout' => 'user/logout',
'cart/checkout' =>'cart/checkout',
'cart/delete/([0-9]+)' => 'cart/delete/$1',
'cart' => 'cart/index',
'admin/product/create' => 'adminProduct/create',
'admin/product/update/([0-9]+)' => 'adminProduct/update/$1',
'admin/product/delete/([0-9]+)' => 'adminProduct/delete/$1',
'admin/category/create' => 'adminCategory/create',
'admin/category/update/([0-9]+)' => 'adminCategory/update/$1',
'admin/category/delete/([0-9]+)' => 'adminCategory/delete/$1',
'admin/product' => 'adminProduct/index',
'admin/category' => 'adminCategory/index',
'admin/order/view/([0-9]+)' => 'adminOrder/view/$1',
'admin/order/update/([0-9]+)' => 'adminOrder/update/$1',
'admin/order/delete/([0-9]+)' => 'adminOrder/delete/$1',
'admin/order' => 'adminOrder/index',
'admin' => 'admin/index',
''=>'site/index' 
];
